version: '3.8'

# --- SERVICIOS ---
services:
  
  # 1. FRONTEND (REACT - VISTA)
  frontend-angel:
    container_name: frontend-angel
    # ********** CORRECCIÓN: Apunta a la carpeta './frontend' **********
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    # *****************************************************************
    ports:
      - "3000:3000"
    depends_on:
      - backend-vera
    networks:
      - app-net

  # 2. BACKEND (NODE.JS / EXPRESS - API)
  backend-vera:
    container_name: backend-vera
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db-angel
      DB_USER: root
      DB_PASS: chame0104
      DB_NAME: chame_db
      PORT: 5000
      NODE_ENV: production
    depends_on:
      - db-angel
    networks:
      - app-net

  # 3. BASE DE DATOS (MYSQL)
  db-angel:
    container_name: db-angel
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: chame0104
      MYSQL_DATABASE: chame_db
    volumes:
      # 1. Persistencia de datos
      - mysql_data_volume:/var/lib/mysql
      # 2. Monta el script SQL para la inicialización automática (Crea la tabla 'people')
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-net

# --- VOLÚMENES ---
volumes:
  mysql_data_volume:
    driver: local

# --- REDES ---
networks:
  app-net:
    driver: bridge